// Reports.js
import React, { useState } from 'react';
import { reportAPI } from '../services/api';

export default function Reports() {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);

  const generate = async () => {
    setLoading(true);
    try { const r = await reportAPI.summary(); setReport(r.data); }
    catch (err) { alert('Error generating report'); }
    finally { setLoading(false); }
  };

  return (
    <div>
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div><h1 className="page-title">Performance Reports</h1><p className="page-sub">Generate system summary reports</p></div>
        <button className="btn btn-primary" onClick={generate} disabled={loading}>{loading ? 'Generating...' : '⬇ Generate Report'}</button>
      </div>
      {!report ? <div className="card"><div className="empty-state"><h3>No report generated</h3><p>Click Generate Report to create a summary</p></div></div> : (
        <div>
          <div className="stats-grid">
            <div className="stat-card"><div className="stat-label">Total Servers</div><div className="stat-value">{report.summary.totalServers}</div></div>
            <div className="stat-card amber"><div className="stat-label">Avg Load</div><div className="stat-value">{report.summary.avgLoad}%</div></div>
            <div className="stat-card red"><div className="stat-label">Total Incidents</div><div className="stat-value">{report.summary.totalIncidents}</div></div>
            <div className="stat-card green"><div className="stat-label">Resolved</div><div className="stat-value">{report.summary.resolvedIncidents}</div></div>
          </div>
          <div className="card" style={{ marginBottom: 16 }}>
            <h3 style={{ fontSize: 14, fontWeight: 600, marginBottom: 12 }}>Server Summary</h3>
            <table>
              <thead><tr><th>Server</th><th>Status</th><th>Load</th><th>Uptime</th></tr></thead>
              <tbody>
                {report.servers.map((s, i) => (
                  <tr key={i}>
                    <td style={{ fontFamily: 'monospace', fontWeight: 500 }}>{s.name}</td>
                    <td><span className={`badge ${s.status === 'active' ? 'badge-green' : 'badge-gray'}`}>{s.status}</span></td>
                    <td>{Math.round(s.load)}%</td>
                    <td>{s.uptime}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div style={{ fontSize: 11, color: '#9ca3af', textAlign: 'right' }}>
            Generated by {report.generatedBy} at {new Date(report.generatedAt).toLocaleString()}
          </div>
        </div>
      )}
    </div>
  );
}
